# Generated by Django 3.2.5 on 2021-07-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(through='posts.PostCategories', to='posts.Category'),
        ),
    ]
